apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka-exporter
  namespaceSelector:
    matchNames:
      - strimzi
  endpoints:
    - port: tcp-prometheus
      interval: 10s
